# Generated by Django 5.1.5 on 2025-01-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='studentlead',
        ),
        migrations.AddField(
            model_name='project',
            name='studentOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='student.studentlead'),
        ),
        migrations.AlterField(
            model_name='studentlead',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.supervisor'),
        ),
        migrations.CreateModel(
            name='StudentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('Leaderlead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='student.studentlead')),
            ],
        ),
    ]
